version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 314146327659.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t aws-cicd-sample .
      - docker tag aws-cicd-sample:latest 314146327659.dkr.ecr.ap-south-1.amazonaws.com/aws-cicd-sample:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 314146327659.dkr.ecr.ap-south-1.amazonaws.com/aws-cicd-sample:latest
